definitions:
  main.Lecture:
    properties:
      day:
        type: integer
      duration:
        type: integer
      id:
        type: integer
      lecturer:
        type: string
      subject_id:
        type: integer
      time:
        type: integer
    type: object
  main.Practice:
    properties:
      day:
        type: integer
      duration:
        type: integer
      id:
        type: integer
      lecture_id:
        type: integer
      practice_teacher:
        type: string
      time:
        type: integer
    type: object
  main.Subject:
    properties:
      code:
        type: string
      id:
        type: integer
      subject_name:
        type: string
    type: object
host: localhost:7070
info:
  contact:
    name: Sanzhar
    url: https://t.me/svnzh1k
  title: schedule-maker-api
  version: "1.0"
paths:
  /lectures/{subjectId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Subject ID
        in: path
        name: subjectId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Lecture'
            type: array
      summary: Получить список лекций
      tags:
      - Lectures
  /practices/{lectureId}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Lecture ID
        in: path
        name: lectureId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Practice'
            type: array
      summary: Получить список практисов
      tags:
      - Practices
  /subjects:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Subject'
            type: array
      summary: Получить список предметов
      tags:
      - Subjects
swagger: "2.0"
