INSERT INTO subject (code, subject_name) VALUES ('INF 395', 'Advanced project for information systems');
INSERT INTO subject (code, subject_name) VALUES ('INF 367', 'Elect.5 3D Animation');
INSERT INTO subject (code, subject_name) VALUES ('INF 369', 'Elect.5 Data visuallisation and storytelling');
INSERT INTO subject (code, subject_name) VALUES ('INF 371', 'Elect.5 Automation in Testing');
INSERT INTO subject (code, subject_name) VALUES ('INF 373', 'Elect.5 Web back');
INSERT INTO subject (code, subject_name) VALUES ('INF 424', 'Elect.5 AI services on AWS');
INSERT INTO subject (code, subject_name) VALUES ('INF 433', 'Elect.5 ICT in Agriculture');
INSERT INTO subject (code, subject_name) VALUES ('INF 356', 'Elect.6 Game Development 1');
INSERT INTO subject (code, subject_name) VALUES ('CSS 439', 'Elect.6 Distributed Big Data Systems');
INSERT INTO subject (code, subject_name) VALUES ('INF 430', 'Elect.6 Fundamentals of SOC');
INSERT INTO subject (code, subject_name) VALUES ('INF 432', 'Elect.6 Entrepreneurship');  
INSERT INTO subject (code, subject_name) VALUES ('INF 368', 'Elect.6 The Go programming language');
INSERT INTO subject (code, subject_name) VALUES ('INF 379', 'Elect.6 Introduction to self-driving cars');
INSERT INTO subject (code, subject_name) VALUES ('INF 362', 'Elect.6 Design for Manufacture');
INSERT INTO subject (code, subject_name) VALUES ('CSS 415', 'Elect.6 IT Management');
INSERT INTO subject (code, subject_name) VALUES ('INF 375', 'Elect.7 Artificial Intelligence');
INSERT INTO subject (code, subject_name) VALUES ('INF 300', 'Elect.7 Product management');
INSERT INTO subject (code, subject_name) VALUES ('INF 363', 'Elect.7 Advanced VFX and Post Production');
INSERT INTO subject (code, subject_name) VALUES ('INF 391', 'Elect.7 Management in IT Ops');
INSERT INTO subject (code, subject_name) VALUES ('INF 392', 'Elect.7 Blockchain technology');
INSERT INTO subject (code, subject_name) VALUES ('INF 394', 'Elect.7 Introduction to Geographic Information Systems');
INSERT INTO subject (code, subject_name) VALUES ('MDE 151', 'Political Science');
INSERT INTO subject (code, subject_name) VALUES ('MDE 152', 'Sociology');
INSERT INTO subject (code, subject_name) VALUES ('MDE 172', 'Philosophy');